#include <iostream>
#include <vector>
#include <string>
#include <chrono>

#include "queues/msgQueueMutex.h"
#include "queues/msgQueueTwoLock.h"
#include "queues/msgQueueSharded.h"
#include "queues/msgQueueAtomic.h"
#include "queues/msgQueueAtomicSharded.h"
#include "utils/StressHarness.h"
#include "utils/metrics.h"
#include "utils/StatsSummary.h"

/**
 * @brief Execute a benchmark run for the given queue type.
 *
 * Instantiates the queue, runs a StressHarness workload with
 * configurable producers, consumers, and iteration count, prints
 * summary statistics, and appends a row to results.csv.
 *
 * @tparam QueueType Message queue implementation to benchmark.
 * @param label Descriptive label for result reporting.
 * @param producers Number of producer threads.
 * @param consumers Number of consumer threads.
 * @param msgs_per_producer Messages generated by each producer.
 * @param num_runs Number of repetitions of the workload.
 */
template <typename QueueType>
void run_benchmark(const std::string& label,
                   size_t producers,
                   size_t consumers,
                   size_t msgs_per_producer,
                   size_t num_runs)
{
    std::cout << "\n=== Running benchmark: " << label << " ===\n";

    QueueType queue;
    StressHarness<QueueType> harness(producers, consumers, msgs_per_producer, num_runs);

    uint64_t t0 = Instrumentation::now_ns();
    harness.run(queue);
    uint64_t t1 = Instrumentation::now_ns();

    double sec = double(t1 - t0) / 1e9;
    std::cout << "Total time: " << sec << " sec\n";

    StatsSummary summary = computeStats(harness.final_metrics);
    printStats(summary);

    write_csv_row("results.csv",
                  label,
                  summary,
                  producers,
                  consumers,
                  msgs_per_producer,
                  num_runs);

    std::cout << "============================================================\n";
}

/**
 * @brief Program entry point for queue benchmarking suite.
 *
 * Accepts optional command line arguments to override producer count,
 * consumer count, messages per producer, and number of runs.
 * Benchmarks all queue variants in a fixed order and writes results
 * to stdout and results.csv.
 */
int main(int argc, char** argv) {

    size_t producers = 8;
    size_t consumers = 8;
    size_t msgs_per_producer = 300;
    size_t num_runs = 1000;

    if (argc >= 5) {
        producers = std::strtoull(argv[1], nullptr, 10);
        consumers = std::strtoull(argv[2], nullptr, 10);
        msgs_per_producer = std::strtoull(argv[3], nullptr, 10);
        num_runs = std::strtoull(argv[4], nullptr, 10);
    } else if (argc != 1) {
        std::cerr << "Usage: " << argv[0]
                  << " <producers> <consumers> <msgs_per_producer> <num_runs>\n";
        return 1;
    }

    run_benchmark<MessageQueueMutex>(
        "Single Mutex Queue (Linked List)",
        producers, consumers, msgs_per_producer, num_runs);

    run_benchmark<MessageQueueTwoLock>(
        "Two Lock Queue",
        producers, consumers, msgs_per_producer, num_runs);

    run_benchmark<MessageQueueSharded>(
        "Sharded Queue with Two Lock Scheme",
        producers, consumers, msgs_per_producer, num_runs);

    run_benchmark<MessageQueueAtomic>(
        "Atomic Queue",
        producers, consumers, msgs_per_producer, num_runs);

    run_benchmark<MessageQueueAtomicSharded>(
        "Sharded Atomic Queue",
        producers, consumers, msgs_per_producer, num_runs);

    return 0;
}
